name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Clippy clippy
      run: cargo clippy --tests --no-deps -- -D warnings
    
    - name: Create python venv
      run: python -m venv .venv --prompt technicalysis && source .venv/bin/activate

    - name: Add python requirements
      run: pip install -r requirements-dev.txt
    
    - name: Build python package with maturin
      run: maturin develop --release

    - name: Run unit & property tests
      run: cargo test --verbose

    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: llvm-tools-preview
        override: false
  
    - name: Install cargo-fuzz
      run: cargo +nightly install cargo-fuzz

    - name: Fuzz tests
      run: |
        chmod +x fuzz/run_all.sh
        cargo +nightly --version
        bash fuzz/run_all.sh
    
    - name: Build 
      run: pytest
